### ISSUE TITLE
TypeError: Cannot set property 'htmlWithMacroProcessing' of undefined

### ISSUE THREAD

**Issue by kasperkronborg** [SargoDarya/bungie-platform#1]
Just by installing and running your example in the README I get the following error:

~/dev/njs/vod/node_modules/bungie-platform/lib/platform.js:11434
    a.fn.htmlWithMacroProcessing = function(d) {
                                 ^
TypeError: Cannot set property 'htmlWithMacroProcessing' of undefined
    at ~/dev/njs/vod/node_modules/bungie-platform/lib/platform.js:11434:34
    at module.exports (~/dev/njs/vod/node_modules/bungie-platform/lib/platform.js:11478:5)
    at Object.<anonymous> (~/dev/njs/vod/index.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by kasperkronborg** [comment]
I solved it by pointing to ./platform.js in the package.js file instead of pointing to lib/platform.js.

**Comment by ToothpickFactory** [comment]
That worked for me as well. Small correction, it's package.json not .js
